version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    volumes:
      - ./backend_fast:/code/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: fastapi_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: adminer
    container_name: fastapi_pgadmin
    ports:
      - "5050:8080"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
